export interface Question {
  id: string;
  text: string;
  options: string[];
  correctAnswerIndex: number;
  explanation?: string;
}

export interface Topic {
  id: string;
  name: string;
  timeLimit?: number; // minutes
}

export interface Subject {
  id: string;
  name: string;
  icon: string;
  color: string;
  bg: string;
  topics: Topic[];
}

export const SUBJECTS: Subject[] = [
  {
    id: "rajasthan_geography",
    name: "Rajasthan Geography",
    icon: "map",
    color: "text-amber-500",
    bg: "bg-amber-50 dark:bg-amber-950/30",
    topics: [
      { id: "physical_features", name: "Physical Features", timeLimit: 15 },
      { id: "climate", name: "Climate of Rajasthan", timeLimit: 12 },
    ]
  },
  {
    id: "rajasthan_culture",
    name: "Rajasthan Culture & Heritage",
    icon: "music",
    color: "text-pink-500",
    bg: "bg-pink-50 dark:bg-pink-950/30",
    topics: [
      { id: "folk_dances", name: "Folk Dances", timeLimit: 10 },
      { id: "forts", name: "Forts and Palaces", timeLimit: 20 },
    ]
  },
  {
    id: "indian_polity",
    name: "Indian Polity",
    icon: "book",
    color: "text-blue-500",
    bg: "bg-blue-50 dark:bg-blue-950/30",
    topics: [
      { id: "union_executive", name: "Union Govt & Executive", timeLimit: 25 },
      { id: "constitutional_posts", name: "Constitutional Posts", timeLimit: 25 },
      { id: "parliament", name: "Parliament & Buildings", timeLimit: 25 },
      { id: "lok_sabha", name: "Lok Sabha Structure", timeLimit: 25 },
    ]
  },
  {
    id: "science_tech",
    name: "Science & Technology",
    icon: "cpu",
    color: "text-purple-500",
    bg: "bg-purple-50 dark:bg-purple-950/30",
    topics: []
  }
];

export const getSubjectById = (id: string) => SUBJECTS.find(s => s.id === id);

// Fetch questions from the compiled JSON (generated by scripts/organize.ts)
// It will fail gracefully if the file hasn't been generated yet
export async function getQuestions(subjectId: string, topicId: string): Promise<Question[]> {
  try {
    const dataModule = await import('./generated_questions.json');
    const db = (dataModule.default || dataModule) as Record<string, Record<string, Question[]>>;
    return db[subjectId]?.[topicId] || [];
  } catch (err) {
    console.warn(`Could not load questions for ${subjectId}-${topicId}`, err);
    return [];
  }
}
