import {
  Users,
  MessageSquare,
  FileText,
  Video,
  Settings,
  Bell,
  Search,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  Target,
  Trophy,
  Activity,
  User,
  LogOut,
  Moon,
  Sun,
  Award,
  BookOpen,
  CheckCircle,
  HelpCircle,
  Clock,
  Menu,
  X,
  Plus,
  ArrowRight,
  ArrowLeft,
  Brain,
  History,
  TrendingUp,
  Zap,
  Pin,
  Phone,
  MoreVertical,
  ExternalLink,
  Paperclip,
  Send,
  FileUp,
  Edit3,
  CloudUpload,
  Archive,
  Wand2,
  FileSpreadsheet,
  Code,
  Edit2,
  Lightbulb,
  Bold,
  Italic,
  List,
  Sigma,
  Calendar,
  Download,
  Fingerprint,
  BarChart,
  ArrowUp,
  AlertTriangle,
  AlertCircle,
  RefreshCcw,
  Bookmark
} from "lucide-react";

export const Icons = {
  users: Users,
  message: MessageSquare,
  fileText: FileText,
  video: Video,
  settings: Settings,
  bell: Bell,
  search: Search,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  target: Target,
  trophy: Trophy,
  activity: Activity,
  user: User,
  logout: LogOut,
  moon: Moon,
  sun: Sun,
  award: Award,
  bookOpen: BookOpen,
  checkCircle: CheckCircle,
  helpCircle: HelpCircle,
  clock: Clock,
  menu: Menu,
  close: X,
  plus: Plus,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  brain: Brain,
  history: History,
  trendingUp: TrendingUp,
  zap: Zap,
  pin: Pin,
  phone: Phone,
  moreVertical: MoreVertical,
  externalLink: ExternalLink,
  paperclip: Paperclip,
  send: Send,
  fileUp: FileUp,
  edit3: Edit3,
  cloudUpload: CloudUpload,
  archive: Archive,
  wand2: Wand2,
  fileSpreadsheet: FileSpreadsheet,
  code: Code,
  edit2: Edit2,
  lightbulb: Lightbulb,
  bold: Bold,
  italic: Italic,
  list: List,
  sigma: Sigma,
  calendar: Calendar,
  download: Download,
  fingerprint: Fingerprint,
  barChart: BarChart,
  arrowUp: ArrowUp,
  alertTriangle: AlertTriangle,
  alertCircle: AlertCircle,
  refreshCcw: RefreshCcw,
  bookmark: Bookmark,
};

// Extracted from sign-in HTML as requested for Central App Logo
export function AppLogoIcon({ className }: { className?: string }) {
  return (
    <svg 
      viewBox="0 0 24 24" 
      fill="currentColor" 
      className={className || "w-8 h-8"}
      xmlns="http://www.w3.org/2000/svg"
    >
      <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm5 11h-4v4h-2v-4H7v-2h4V7h2v4h4v2z" />
    </svg>
  );
}
